### ISSUE TITLE
cubo

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/Python#2]
aggiustare

**Comment by Giandomenico-bit** [comment]
Non avevo proprio visto che i numeri chiesti da tastiera dovevano esseri interi. Comunque ho corretto tutti i programmi

**Comment by FabioZTessitore** [comment]
a parte il fatto che devono essere interi perché richiesto dall'esercizio, ma la funzione `input()` in py3 restituisce una stringa, non un numero
