### ISSUE TITLE
paridisp

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/Python#3]
questa istruzione è corretta ma la capisce solo chi conosce la rappresentazione binaria dei numeri e l'operatore `&`

```py
if value & 1 :
```

meglio sostituirla con qualcosa di più comprensibile. I codici devono essere facili da leggere

**Comment by Giandomenico-bit** [comment]
Si ha perfettamente ragione. Tuttavia, utilizzando questo metodo, in
termini di prestazioni, è molto più efficiente rispetto all’operatore
modulo. O sbaglio?

Il giorno gio 31 ott 2019 alle 08:01 Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
sicuramente, ma non è questo il caso di pensare ad ottimizzazioni.
Poi sei sicuro che l'interprete non lo faccia al posto tuo?

**Comment by Giandomenico-bit** [comment]
Ho capito. Provvedo subito a correggere il codice

Il giorno gio 31 ott 2019 alle 08:07 Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
non per essere pesante, ma per darti la giusta disciplina.
```py
if value % 2:
```

`value % 2` cosa? bisogna sempre sapere che se è "non zero" allora ok

**Comment by Giandomenico-bit** [comment]
Perdonate la mia superficialità

**Comment by FabioZTessitore** [comment]
nessun problema, siamo qui per questo
