### ISSUE TITLE
primogrado

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/Python#4]
```py
a = int( a )
b = int( b )
...
    x = -( b / a )
```

Questo codice funziona, ma solo perché in py3 hanno deciso che una divisione tra int è float. Siccome non succede in altri linguaggi è meglio mettere un cast ` x = -float(b)/float(a)`

**Comment by Giandomenico-bit** [comment]
Sisi qua non ci ho fatto proprio caso.
