### ISSUE TITLE
secgrado

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/Python#5]
il calcolo del delta va fatto nell'else, prima non ha senso

**Comment by FabioZTessitore** [comment]
ajajajajajajaj

**Comment by Giandomenico-bit** [comment]
Come sono distratto. Un mese che studio programmazione e faccio ancora questi errori

**Comment by FabioZTessitore** [comment]
hai capito qual è il problema?

**Comment by Giandomenico-bit** [comment]
No

Il giorno gio 31 ott 2019 alle 08:57 Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
sei nell'else ... quindi

**Comment by Giandomenico-bit** [comment]
Ma sempre per quando riguarda il delta?

**Comment by FabioZTessitore** [comment]
si

**Comment by Giandomenico-bit** [comment]
Ho fatto il calcolo del delta nell’else come giustamente mi avete detto. Ma non riesco a capire qual’è il problema

**Comment by FabioZTessitore** [comment]
prova a mandarlo in esecuzione

**Comment by Giandomenico-bit** [comment]
Non ho potuto testarlo perchè ero a lezione. Comunque ho risolto. Il fatto che python non includa le parentesi mi confonde molto

**Comment by FabioZTessitore** [comment]
si, ma ti costringe ad essere ordinato :)
